export const LEGAL_CORPUS = [
  {
    id: "frcp-rule-11",
    title: "Federal Rule of Civil Procedure 11",
    jurisdiction: "United States federal courts",
    type: "rule",
    citation: "Fed. R. Civ. P. 11",
    sourceUrl: "https://www.law.cornell.edu/rules/frcp/rule_11",
    aliases: ["Rule 11", "FRCP 11", "Fed. R. Civ. P. 11"],
    text:
      "Federal Rule of Civil Procedure 11 requires an attorney or unrepresented party who presents a paper to certify that it is not presented for an improper purpose, that legal contentions are warranted by existing law or a nonfrivolous argument, and that factual contentions have evidentiary support or will likely have support after investigation."
  },
  {
    id: "mata-v-avianca",
    title: "Mata v. Avianca, Inc.",
    jurisdiction: "S.D.N.Y.",
    type: "case",
    citation: "678 F. Supp. 3d 443 (S.D.N.Y. 2023)",
    sourceUrl: "https://www.courtlistener.com/opinion/9534506/mata-v-avianca-inc/",
    aliases: ["Mata v. Avianca", "Mata v Avianca", "Avianca case"],
    text:
      "In Mata v. Avianca, Inc., the court sanctioned attorneys after a filing relied on nonexistent judicial opinions generated by ChatGPT. The court emphasized that technological assistance does not excuse counsel from the duty to verify cited authority."
  },
  {
    id: "fed-evidence-201",
    title: "Federal Rule of Evidence 201",
    jurisdiction: "United States federal courts",
    type: "rule",
    citation: "Fed. R. Evid. 201",
    sourceUrl: "https://www.law.cornell.edu/rules/fre/rule_201",
    aliases: ["Rule 201", "FRE 201", "Fed. R. Evid. 201", "judicial notice"],
    text:
      "Federal Rule of Evidence 201 governs judicial notice of adjudicative facts. A court may judicially notice a fact that is not subject to reasonable dispute because it is generally known within the trial court's territorial jurisdiction or can be accurately and readily determined from sources whose accuracy cannot reasonably be questioned."
  },
  {
    id: "india-article-14",
    title: "Constitution of India, Article 14",
    jurisdiction: "India",
    type: "constitution",
    citation: "India Const. art. 14",
    sourceUrl: "https://www.indiacode.nic.in/handle/123456789/15240",
    aliases: ["Article 14", "equality before law", "equal protection of the laws"],
    text:
      "Article 14 of the Constitution of India provides that the State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India."
  },
  {
    id: "india-article-21",
    title: "Constitution of India, Article 21",
    jurisdiction: "India",
    type: "constitution",
    citation: "India Const. art. 21",
    sourceUrl: "https://www.indiacode.nic.in/handle/123456789/15240",
    aliases: ["Article 21", "right to life", "personal liberty"],
    text:
      "Article 21 of the Constitution of India states that no person shall be deprived of life or personal liberty except according to procedure established by law."
  },
  {
    id: "maneka-gandhi",
    title: "Maneka Gandhi v. Union of India",
    jurisdiction: "Supreme Court of India",
    type: "case",
    citation: "(1978) 1 SCC 248",
    sourceUrl: "https://indiankanoon.org/doc/1766147/",
    aliases: ["Maneka Gandhi", "Maneka Gandhi v Union of India"],
    text:
      "In Maneka Gandhi v. Union of India, the Supreme Court of India gave Article 21 a broader interpretation and connected personal liberty with fair, just, and reasonable procedure."
  },
  {
    id: "pocso-section-29",
    title: "Protection of Children from Sexual Offences Act, Section 29",
    jurisdiction: "India",
    type: "statute",
    citation: "POCSO Act, 2012, s. 29",
    sourceUrl: "https://www.indiacode.nic.in/handle/123456789/2079",
    aliases: ["POCSO Section 29", "Section 29 POCSO", "POCSO Act"],
    text:
      "Section 29 of the Protection of Children from Sexual Offences Act creates a presumption regarding certain offences when a person is prosecuted under specified provisions, subject to the accused's right to rebut according to law."
  },
  {
    id: "brown-board",
    title: "Brown v. Board of Education",
    jurisdiction: "United States Supreme Court",
    type: "case",
    citation: "347 U.S. 483 (1954)",
    sourceUrl: "https://supreme.justia.com/cases/federal/us/347/483/",
    aliases: ["Brown v. Board", "Brown v Board of Education"],
    text:
      "Brown v. Board of Education held that state-sponsored racial segregation in public schools violates the Equal Protection Clause of the Fourteenth Amendment."
  }
];

export const MIT_REFERENCE = {
  title: "When AI Gets It Wrong: Addressing AI Hallucinations and Bias",
  publisher: "MIT Sloan Teaching & Learning Technologies",
  url: "https://mitsloanedtech.mit.edu/ai/basics/addressing-ai-hallucinations-and-bias/",
  notes:
    "The article recommends critical evaluation, source diversification, retrieval-based tools, structured prompts, and low-temperature factual generation for reducing hallucination and bias risk."
};
